trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: LIQUIBASE_VERSION
  type: string
  default: '4.23.0'

- name: RUN_STATUS
  type: boolean
  default: true

- name: RUN_VALIDATE
  type: boolean
  default: true

- name: RUN_UPDATE
  type: boolean
  default: true

### DevOps Variable Group examples / convention
# SF_ACCOUNT - abcdefg-sf12345
# SF_LIQUIBASE_CHANGELOG_PATH - liquibase/snowflake/master.yml

#### DevOps Variable Group should be migrated to Key Vault

variables:
- group: 'snowflake-variables'

steps:
- checkout: self

- script: |
    wget https://github.com/liquibase/liquibase/releases/download/v${{ parameters.LIQUIBASE_VERSION }}/liquibase-${{ parameters.LIQUIBASE_VERSION }}.zip
    unzip liquibase-${{ parameters.LIQUIBASE_VERSION }}.zip -d liquibase
    # grant execute permissions
    chmod -R +x $(Build.SourcesDirectory)/liquibase
  displayName: 'Install Liquibase'

### General requirements
# changeLogFile must be a relative path to the pwd SourcesDirectory
# SF_DATABASE.SF_SCHEMA used to load DATABASECHANGELOG and DATABASECHANGELOGLOCK must already exist

### Snowflake specific requirements
# must run: ALTER ACCOUNT SET MULTI_STATEMENT_COUNT = 0; on the executing account to support multi command jdbc changesets (if required)

### Liquibase status - identify changesets that have not been deployed based on reading DATABASECHANGELOG

- ${{ if parameters.RUN_STATUS }}:
  - script: |
      $(Build.SourcesDirectory)/liquibase/liquibase \
      --driver=$(SF_LIQUIBASE_DRIVER_NAME) \
      --changeLogFile=$(SF_LIQUIBASE_CHANGELOG_PATH) \
      --url="jdbc:snowflake://$(SF_ACCOUNT).snowflakecomputing.com/?db=$(SF_DATABASE)&schema=$(SF_SCHEMA)&warehouse=$(SF_WAREHOUSE)&role=$(SF_ROLE)" \
      --username=$(SF_USERNAME) \
      --password=$(SF_PASSWORD) \
      status
    displayName: 'Run Liquibase Status Command'

### Liquibase validate - validate SQL syntax of the changesets to be deployed

- ${{ if parameters.RUN_VALIDATE }}:
  - script: |
      $(Build.SourcesDirectory)/liquibase/liquibase \
      --driver=$(SF_LIQUIBASE_DRIVER_NAME) \
      --changeLogFile=$(SF_LIQUIBASE_CHANGELOG_PATH) \
      --url="jdbc:snowflake://$(SF_ACCOUNT).snowflakecomputing.com/?db=$(SF_DATABASE)&schema=$(SF_SCHEMA)&warehouse=$(SF_WAREHOUSE)&role=$(SF_ROLE)" \
      --username=$(SF_USERNAME) \
      --password=$(SF_PASSWORD) \
      validate
    displayName: 'Run Liquibase Validate Command'

### Liquibase update - Deploy the undeployed changesets to Snowflake

- ${{ if parameters.RUN_UPDATE }}:
  - script: |
      $(Build.SourcesDirectory)/liquibase/liquibase \
      --driver=$(SF_LIQUIBASE_DRIVER_NAME) \
      --changeLogFile=$(SF_LIQUIBASE_CHANGELOG_PATH) \
      --url="jdbc:snowflake://$(SF_ACCOUNT).snowflakecomputing.com/?db=$(SF_DATABASE)&schema=$(SF_SCHEMA)&warehouse=$(SF_WAREHOUSE)&role=$(SF_ROLE)" \
      --username=$(SF_USERNAME) \
      --password=$(SF_PASSWORD) \
      update
    displayName: 'Run Liquibase Update Command'
