CREATE DATABASE IF NOT EXISTS DEMO_DB;
CREATE SCHEMA IF NOT EXISTS DEMO_SCHEMA;
CREATE SCHEMA IF NOT EXISTS DEMO_SCHEMA2;
CREATE SCHEMA IF NOT EXISTS DEMO_SCHEMA3;
CREATE SCHEMA IF NOT EXISTS DEMO_SCHEMA4;